import { useState, type FormEvent } from "react";
import { Bar, BarChart, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { AlertCircle, CalendarRange, CheckCircle2, Clock3, Headphones, Info, Loader2, Search, ServerCrash, UserRound, UsersRound, X } from "lucide-react";
import { carregarChamadosSults, ehDepartamentoTi, nomeAssunto, SITUACOES, type ChamadoSultsAnalitico } from "../services/chamadosSults";
import { useThemeContext } from "../hooks/ThemeContext";

const CORES = ["#2563eb", "#16a34a", "#7c3aed", "#d97706", "#dc2626", "#0891b2"];
function agrupar(valores: string[]) { const mapa = new Map<string, number>(); valores.forEach((valor) => mapa.set(valor, (mapa.get(valor) ?? 0) + 1)); return [...mapa].map(([nome, total]) => ({ nome, total })).sort((a, b) => b.total - a.total); }
function data(valor?: string) { return valor ? new Date(valor).toLocaleString("pt-BR", { dateStyle: "short", timeStyle: "short" }) : "—"; }
function dataInput(valor: Date) { return `${valor.getFullYear()}-${String(valor.getMonth() + 1).padStart(2, "0")}-${String(valor.getDate()).padStart(2, "0")}`; }
function periodoInicial() { const fim = new Date(); const inicio = new Date(); inicio.setDate(inicio.getDate() - 30); return { inicio: dataInput(inicio), fim: dataInput(fim) }; }

export default function ChamadosPage() {
  const { dark } = useThemeContext();
  const periodoPadrao = periodoInicial();
  const [inicio, setInicio] = useState(periodoPadrao.inicio); const [fim, setFim] = useState(periodoPadrao.fim);
  const [chamados, setChamados] = useState<ChamadoSultsAnalitico[]>([]); const [loading, setLoading] = useState(false); const [consultado, setConsultado] = useState(false); const [erro, setErro] = useState(""); const [aviso, setAviso] = useState(""); const [cache, setCache] = useState(false);
  const [busca, setBusca] = useState(""); const [responsavel, setResponsavel] = useState("Todos"); const [assunto, setAssunto] = useState("Todos"); const [apoio, setApoio] = useState("Todos"); const [situacao, setSituacao] = useState("Todos");

  const carregar = async (event?: FormEvent) => {
    event?.preventDefault();
    if (!inicio || !fim) { setErro("Informe a data inicial e a data final."); return; }
    if (inicio > fim) { setErro("A data inicial não pode ser posterior à data final."); return; }
    setLoading(true); setErro(""); setAviso("");
    try {
      const resultado = await carregarChamadosSults({ inicio, fim });
      setChamados(resultado.data.filter(ehDepartamentoTi)); setCache(resultado.cache); setConsultado(true);
      setAviso(resultado.stale ? `Exibindo a última consulta disponível. ${resultado.aviso ?? "A atualização não pôde ser concluída."}` : "");
    } catch (e) {
      setErro(e instanceof Error ? e.message : "Erro ao carregar chamados."); setConsultado(true);
    } finally { setLoading(false); }
  };

  const responsaveis = [...new Set(chamados.map((item) => item.responsavel?.nome).filter((item): item is string => Boolean(item)))].sort();
  const assuntos = [...new Set(chamados.map(nomeAssunto))].sort();
  const apoios = [...new Set(chamados.flatMap((item) => item.apoio?.map((registro) => registro.pessoa?.nome).filter((nome): nome is string => Boolean(nome)) ?? []))].sort();
  const termo = busca.trim().toLocaleLowerCase("pt-BR");
  const dados = chamados.filter((item) => { const nomesApoio = item.apoio?.map((registro) => registro.pessoa?.nome).filter(Boolean) ?? []; const texto = [item.id, item.titulo, item.solicitante?.nome, item.responsavel?.nome, nomeAssunto(item), item.departamento?.nome, item.unidade?.nome, item.unidade?.nomeFantasia, ...nomesApoio].join(" ").toLocaleLowerCase("pt-BR"); return (!termo || texto.includes(termo)) && (responsavel === "Todos" || item.responsavel?.nome === responsavel) && (assunto === "Todos" || nomeAssunto(item) === assunto) && (apoio === "Todos" || nomesApoio.includes(apoio)) && (situacao === "Todos" || String(item.situacao) === situacao); });
  const limparFiltros = () => { setBusca(""); setResponsavel("Todos"); setAssunto("Todos"); setApoio("Todos"); setSituacao("Todos"); };
  const limparConsulta = () => { const padrao = periodoInicial(); setInicio(padrao.inicio); setFim(padrao.fim); setChamados([]); setConsultado(false); setErro(""); setAviso(""); limparFiltros(); };
  const porResponsavel = agrupar(dados.map((item) => item.responsavel?.nome ?? "Sem responsável")).slice(0, 8); const porAssunto = agrupar(dados.map(nomeAssunto)).slice(0, 8); const porSituacao = agrupar(dados.map((item) => SITUACOES[item.situacao] ?? `Situação ${item.situacao}`));
  const tooltip = { backgroundColor: dark ? "#111827" : "#fff", border: `1px solid ${dark ? "#374151" : "#e5e7eb"}`, borderRadius: 8, fontSize: 12 };
  const limiteAtingido = erro.toLocaleLowerCase("pt-BR").includes("limit") || erro.includes("429");

  return <div className="page"><div className="page-header gap-4"><div><h1 className="page-title">Fluxo de chamados TI</h1><p className="page-subtitle">Consulte um período específico e analise responsáveis, assuntos, situações e apoios.</p></div><span className="badge badge-info">Consulta sob demanda</span></div>
    <form onSubmit={carregar} className="card mb-5 p-5"><div className="mb-4 flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-brand-50 text-brand-600"><CalendarRange className="h-5 w-5" /></div><div><h2 className="text-sm font-semibold text-gray-900">Período de abertura</h2><p className="mt-0.5 text-xs text-gray-500">A SULTS só será consultada quando você clicar em Buscar chamados.</p></div></div><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-[minmax(190px,0.7fr)_minmax(190px,0.7fr)_minmax(0,1fr)_auto_auto]"><label><span className="mb-1.5 block text-xs font-medium text-gray-600">Data inicial</span><input type="date" className="input" value={inicio} max={fim} onChange={(e) => setInicio(e.target.value)} /></label><label><span className="mb-1.5 block text-xs font-medium text-gray-600">Data final</span><input type="date" className="input" value={fim} min={inicio} onChange={(e) => setFim(e.target.value)} /></label><div className="flex items-end gap-2">{[7, 30, 90].map((dias) => <button key={dias} type="button" onClick={() => { const final = new Date(); const inicial = new Date(); inicial.setDate(inicial.getDate() - dias); setInicio(dataInput(inicial)); setFim(dataInput(final)); }} className="btn-secondary flex-1 whitespace-nowrap px-3 text-xs">{dias} dias</button>)}</div><button type="submit" disabled={loading} className="btn-primary flex items-center justify-center gap-2 self-end whitespace-nowrap">{loading ? <Loader2 className="h-4 w-4 animate-spin" /> : <Search className="h-4 w-4" />} Buscar chamados</button><button type="button" onClick={limparConsulta} className="btn-secondary flex items-center justify-center gap-2 self-end"><X className="h-4 w-4" /> Limpar</button></div></form>

    {aviso && <div className="mb-5 flex items-start gap-3 rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-800"><Info className="mt-0.5 h-5 w-5 shrink-0" /><div><p className="font-semibold">Dados preservados no cache</p><p className="mt-1 text-xs leading-5">{aviso}</p></div></div>}
    {erro && <div className="card mb-5 overflow-hidden border-amber-200"><div className="flex flex-col gap-5 p-6 sm:flex-row sm:items-center"><div className="flex h-12 w-12 shrink-0 items-center justify-center rounded-2xl bg-amber-100 text-amber-700"><ServerCrash className="h-6 w-6" /></div><div className="min-w-0 flex-1"><p className="font-semibold text-gray-900">{limiteAtingido ? "A SULTS está limitando as consultas" : "Não foi possível consultar a SULTS"}</p><p className="mt-1 text-sm leading-6 text-gray-500">{limiteAtingido ? "Aguarde alguns instantes ou reduza o período selecionado antes de tentar novamente." : erro}</p></div><button type="button" onClick={() => void carregar()} disabled={loading} className="btn-secondary flex shrink-0 items-center justify-center gap-2"><Search className="h-4 w-4" /> Tentar novamente</button></div>{limiteAtingido && <div className="border-t border-amber-100 bg-amber-50 px-6 py-3 text-xs text-amber-800"><AlertCircle className="mr-1.5 inline h-3.5 w-3.5" /> Períodos menores exigem menos páginas da API e retornam mais rapidamente.</div>}</div>}

    {!consultado && !loading && <section className="card flex min-h-72 flex-col items-center justify-center p-10 text-center"><div className="flex h-16 w-16 items-center justify-center rounded-2xl bg-blue-50 text-blue-600"><CalendarRange className="h-8 w-8" /></div><h2 className="mt-5 text-lg font-semibold text-gray-900">Escolha o período da análise</h2><p className="mt-2 max-w-lg text-sm leading-6 text-gray-500">Nenhum chamado é carregado automaticamente ao abrir esta aba. Selecione as datas acima e faça a consulta quando precisar.</p></section>}
    {loading && !chamados.length && <section className="card flex min-h-72 items-center justify-center gap-3 p-10 text-sm text-gray-500"><Loader2 className="h-6 w-6 animate-spin text-brand-600" /> Consultando chamados abertos no período...</section>}

    {consultado && !loading && <div className="space-y-5"><div className="card p-4"><div className="grid grid-cols-1 gap-3 sm:grid-cols-2 xl:grid-cols-7"><label className="relative sm:col-span-2"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-gray-400" /><input className="input pl-9" value={busca} onChange={(e) => setBusca(e.target.value)} placeholder="Filtrar os resultados por ID, título, solicitante ou unidade..." /></label><select className="input" value={responsavel} onChange={(e) => setResponsavel(e.target.value)}><option>Todos</option>{responsaveis.map((item) => <option key={item}>{item}</option>)}</select><select className="input" value={assunto} onChange={(e) => setAssunto(e.target.value)}><option>Todos</option>{assuntos.map((item) => <option key={item}>{item}</option>)}</select><select className="input" value={apoio} onChange={(e) => setApoio(e.target.value)}><option>Todos</option>{apoios.map((item) => <option key={item}>{item}</option>)}</select><select className="input" value={situacao} onChange={(e) => setSituacao(e.target.value)}><option value="Todos">Todos</option>{Object.entries(SITUACOES).map(([valor, nome]) => <option key={valor} value={valor}>{nome}</option>)}</select><button type="button" onClick={limparFiltros} className="btn-secondary flex w-full items-center justify-center gap-2"><X className="h-4 w-4" /> Limpar filtros</button></div></div>
      <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[{ label: "Chamados filtrados", value: dados.length, icon: Headphones, color: "bg-blue-50 text-blue-600" }, { label: "Novos", value: dados.filter((item) => item.situacao === 1).length, icon: Clock3, color: "bg-amber-50 text-amber-600" }, { label: "Em andamento", value: dados.filter((item) => item.situacao === 4).length, icon: UserRound, color: "bg-violet-50 text-violet-600" }, { label: "Resolvidos/concluídos", value: dados.filter((item) => [2, 3].includes(item.situacao)).length, icon: CheckCircle2, color: "bg-green-50 text-green-600" }].map(({ label, value, icon: Icon, color }) => <div key={label} className="card flex items-center gap-4 p-4"><div className={`flex h-11 w-11 items-center justify-center rounded-xl ${color}`}><Icon className="h-5 w-5" /></div><div><p className="text-xs text-gray-500">{label}</p><p className="mt-1 text-xl font-semibold text-gray-900">{value}</p></div></div>)}</div>
      <div className="grid gap-5 xl:grid-cols-3"><div className="card p-5"><h2 className="mb-4 text-sm font-semibold text-gray-900">Por responsável</h2><ResponsiveContainer width="100%" height={250}><BarChart data={porResponsavel} layout="vertical" margin={{ left: 15, right: 15 }}><XAxis type="number" allowDecimals={false} tick={{ fontSize: 10, fill: dark ? "#9ca3af" : "#6b7280" }} axisLine={false} tickLine={false} /><YAxis type="category" dataKey="nome" width={105} tick={{ fontSize: 10, fill: dark ? "#d1d5db" : "#4b5563" }} axisLine={false} tickLine={false} /><Tooltip contentStyle={tooltip} /><Bar dataKey="total" fill="#2563eb" radius={[0, 4, 4, 0]} /></BarChart></ResponsiveContainer></div><div className="card p-5"><h2 className="mb-4 text-sm font-semibold text-gray-900">Assuntos mais frequentes</h2><ResponsiveContainer width="100%" height={250}><BarChart data={porAssunto} layout="vertical" margin={{ left: 15, right: 15 }}><XAxis type="number" allowDecimals={false} tick={{ fontSize: 10, fill: dark ? "#9ca3af" : "#6b7280" }} axisLine={false} tickLine={false} /><YAxis type="category" dataKey="nome" width={115} tick={{ fontSize: 10, fill: dark ? "#d1d5db" : "#4b5563" }} axisLine={false} tickLine={false} /><Tooltip contentStyle={tooltip} /><Bar dataKey="total" fill="#C41E23" radius={[0, 4, 4, 0]} /></BarChart></ResponsiveContainer></div><div className="card p-5"><h2 className="mb-4 text-sm font-semibold text-gray-900">Situação dos chamados</h2><ResponsiveContainer width="100%" height={205}><PieChart><Pie data={porSituacao} dataKey="total" nameKey="nome" innerRadius={48} outerRadius={76} paddingAngle={3}>{porSituacao.map((_, index) => <Cell key={index} fill={CORES[index % CORES.length]} />)}</Pie><Tooltip contentStyle={tooltip} /></PieChart></ResponsiveContainer><div className="space-y-1.5">{porSituacao.map((item, index) => <div key={item.nome} className="flex items-center justify-between text-[11px]"><span className="flex items-center gap-2 text-gray-500"><span className="h-2 w-2 rounded-full" style={{ background: CORES[index % CORES.length] }} />{item.nome}</span><strong className="text-gray-900">{item.total}</strong></div>)}</div></div></div>
      <section className="card overflow-hidden"><div className="flex items-center justify-between border-b border-gray-100 px-5 py-4"><div><h2 className="text-sm font-semibold text-gray-900">Chamados do TI</h2><p className="mt-1 text-[11px] text-gray-400">Abertos entre {new Date(`${inicio}T12:00:00`).toLocaleDateString("pt-BR")} e {new Date(`${fim}T12:00:00`).toLocaleDateString("pt-BR")}</p></div><span className="text-xs text-gray-400">{cache ? "Dados em cache • " : ""}{dados.length} resultado(s)</span></div><div className="overflow-x-auto"><table className="w-full min-w-[1180px] text-left"><thead className="bg-gray-50 text-[10px] uppercase tracking-wide text-gray-500"><tr><th className="px-5 py-3">Número</th><th className="px-4 py-3">Título</th><th className="px-4 py-3">Situação</th><th className="px-4 py-3">Responsável</th><th className="px-4 py-3">Assunto</th><th className="px-4 py-3">Apoios</th><th className="px-4 py-3">Aberto</th><th className="px-4 py-3">Interações</th></tr></thead><tbody>{dados.map((item) => <tr key={item.id} className="border-t border-gray-100 text-xs hover:bg-gray-50"><td className="whitespace-nowrap px-5 py-3 font-semibold text-gray-900">#{item.id}</td><td className="max-w-80 px-4 py-3"><p className="font-semibold text-gray-900">{item.titulo}</p><p className="mt-1 text-[10px] text-gray-400">{item.solicitante?.nome ?? "Solicitante não informado"} • {item.departamento?.nome ?? "Sem departamento"}</p></td><td className="px-4 py-3"><span className={`badge ${item.situacao === 1 ? "badge-warn" : [2, 3].includes(item.situacao) ? "badge-ok" : "badge-info"}`}>{SITUACOES[item.situacao] ?? item.situacao}</span></td><td className="px-4 py-3 font-medium text-gray-700">{item.responsavel?.nome ?? "Fila / sem responsável"}</td><td className="px-4 py-3 text-gray-600">{nomeAssunto(item)}</td><td className="px-4 py-3"><div className="flex items-center gap-1.5 text-gray-500"><UsersRound className="h-3.5 w-3.5" />{item.apoio?.map((registro) => registro.pessoa?.nome).filter(Boolean).join(", ") || "—"}</div></td><td className="px-4 py-3 text-gray-500">{data(item.aberto)}</td><td className="px-4 py-3 text-gray-500">{(item.countInteracaoPublico ?? 0) + (item.countInteracaoInterno ?? 0)}</td></tr>)}</tbody></table></div>{!dados.length && <p className="p-10 text-center text-sm text-gray-400">Nenhum chamado do departamento de TI encontrado para os filtros selecionados.</p>}</section></div>}
  </div>;
}
