import { useEffect, useState } from "react";
import { Bar, BarChart, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { AlertCircle, CheckCircle2, Clock3, Headphones, Loader2, RefreshCw, Search, UserRound, UsersRound, X } from "lucide-react";
import { carregarChamadosSults, nomeAssunto, SITUACOES, type ChamadoSultsAnalitico } from "../services/chamadosSults";
import { useThemeContext } from "../hooks/ThemeContext";

const CORES = ["#2563eb", "#16a34a", "#7c3aed", "#d97706", "#dc2626", "#0891b2"];
function agrupar(valores: string[]) { const mapa = new Map<string, number>(); valores.forEach((valor) => mapa.set(valor, (mapa.get(valor) ?? 0) + 1)); return [...mapa].map(([nome, total]) => ({ nome, total })).sort((a, b) => b.total - a.total); }
function data(valor?: string) { return valor ? new Date(valor).toLocaleString("pt-BR", { dateStyle: "short", timeStyle: "short" }) : "—"; }

export default function ChamadosPage() {
  const { dark } = useThemeContext();
  const [chamados, setChamados] = useState<ChamadoSultsAnalitico[]>([]); const [loading, setLoading] = useState(true); const [erro, setErro] = useState(""); const [cache, setCache] = useState(false);
  const [busca, setBusca] = useState(""); const [responsavel, setResponsavel] = useState("Todos"); const [assunto, setAssunto] = useState("Todos"); const [apoio, setApoio] = useState("Todos"); const [situacao, setSituacao] = useState("Todos");
  const carregar = (refresh = false) => { setLoading(true); setErro(""); carregarChamadosSults(refresh).then((resultado) => { setChamados(resultado.data); setCache(resultado.cache); }).catch((e) => setErro(e instanceof Error ? e.message : "Erro ao carregar chamados." )).finally(() => setLoading(false)); };
  useEffect(() => {
    carregarChamadosSults()
      .then((resultado) => { setChamados(resultado.data); setCache(resultado.cache); })
      .catch((e) => setErro(e instanceof Error ? e.message : "Erro ao carregar chamados."))
      .finally(() => setLoading(false));
  }, []);
  const responsaveis = [...new Set(chamados.map((item) => item.responsavel?.nome).filter((item): item is string => Boolean(item)))].sort();
  const assuntos = [...new Set(chamados.map(nomeAssunto))].sort();
  const apoios = [...new Set(chamados.flatMap((item) => item.apoio?.map((registro) => registro.pessoa?.nome).filter((nome): nome is string => Boolean(nome)) ?? []))].sort();
  const termo = busca.trim().toLocaleLowerCase("pt-BR");
  const dados = chamados.filter((item) => { const nomesApoio = item.apoio?.map((registro) => registro.pessoa?.nome).filter(Boolean) ?? []; const texto = [item.id, item.titulo, item.solicitante?.nome, item.responsavel?.nome, nomeAssunto(item), item.departamento?.nome, item.unidade?.nome, item.unidade?.nomeFantasia, ...nomesApoio].join(" ").toLocaleLowerCase("pt-BR"); return (!termo || texto.includes(termo)) && (responsavel === "Todos" || item.responsavel?.nome === responsavel) && (assunto === "Todos" || nomeAssunto(item) === assunto) && (apoio === "Todos" || nomesApoio.includes(apoio)) && (situacao === "Todos" || String(item.situacao) === situacao); });
  const limpar = () => { setBusca(""); setResponsavel("Todos"); setAssunto("Todos"); setApoio("Todos"); setSituacao("Todos"); };
  const porResponsavel = agrupar(dados.map((item) => item.responsavel?.nome ?? "Sem responsável")).slice(0, 8); const porAssunto = agrupar(dados.map(nomeAssunto)).slice(0, 8); const porSituacao = agrupar(dados.map((item) => SITUACOES[item.situacao] ?? `Situação ${item.situacao}`));
  const tooltip = { backgroundColor: dark ? "#111827" : "#fff", border: `1px solid ${dark ? "#374151" : "#e5e7eb"}`, borderRadius: 8, fontSize: 12 };

  return <div className="page"><div className="page-header gap-4"><div><h1 className="page-title">Fluxo de chamados TI</h1><p className="page-subtitle">Análise operacional por responsável, assunto, situação e pessoas de apoio.</p></div><button type="button" onClick={() => carregar(true)} disabled={loading} className="btn-secondary flex items-center gap-2">{loading ? <Loader2 className="h-4 w-4 animate-spin" /> : <RefreshCw className="h-4 w-4" />} Atualizar SULTS</button></div>
    {erro && <div className="mb-5 flex items-start gap-2 rounded-xl border border-red-100 bg-red-50 p-4 text-sm text-red-700"><AlertCircle className="mt-0.5 h-4 w-4 shrink-0" /><div><p className="font-medium">Não foi possível consultar o SULTS</p><p className="mt-1 text-xs">{erro}</p></div></div>}
    <div className="card mb-5 p-4"><div className="grid grid-cols-1 gap-3 sm:grid-cols-2 xl:grid-cols-7"><label className="relative sm:col-span-2"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-gray-400" /><input className="input pl-9" value={busca} onChange={(e) => setBusca(e.target.value)} placeholder="Buscar ID, título, solicitante, unidade ou departamento..." /></label><select className="input" value={responsavel} onChange={(e) => setResponsavel(e.target.value)}><option>Todos</option>{responsaveis.map((item) => <option key={item}>{item}</option>)}</select><select className="input" value={assunto} onChange={(e) => setAssunto(e.target.value)}><option>Todos</option>{assuntos.map((item) => <option key={item}>{item}</option>)}</select><select className="input" value={apoio} onChange={(e) => setApoio(e.target.value)}><option>Todos</option>{apoios.map((item) => <option key={item}>{item}</option>)}</select><select className="input" value={situacao} onChange={(e) => setSituacao(e.target.value)}><option value="Todos">Todos</option>{Object.entries(SITUACOES).map(([valor, nome]) => <option key={valor} value={valor}>{nome}</option>)}</select><button type="button" onClick={limpar} className="btn-secondary flex w-full items-center justify-center gap-2"><X className="h-4 w-4" /> Limpar</button></div></div>
    <div className="mb-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[
      { label: "Chamados filtrados", value: dados.length, icon: Headphones, color: "bg-blue-50 text-blue-600" },
      { label: "Novos", value: dados.filter((item) => item.situacao === 1).length, icon: Clock3, color: "bg-amber-50 text-amber-600" },
      { label: "Em andamento", value: dados.filter((item) => item.situacao === 4).length, icon: UserRound, color: "bg-violet-50 text-violet-600" },
      { label: "Resolvidos/concluídos", value: dados.filter((item) => [2, 3].includes(item.situacao)).length, icon: CheckCircle2, color: "bg-green-50 text-green-600" },
    ].map(({ label, value, icon: Icon, color }) => <div key={label} className="card flex items-center gap-4 p-4"><div className={`flex h-11 w-11 items-center justify-center rounded-xl ${color}`}><Icon className="h-5 w-5" /></div><div><p className="text-xs text-gray-500">{label}</p><p className="mt-1 text-xl font-semibold text-gray-900">{value}</p></div></div>)}</div>
    <div className="mb-5 grid gap-5 xl:grid-cols-3"><div className="card p-5"><h2 className="mb-4 text-sm font-semibold text-gray-900">Por responsável</h2><ResponsiveContainer width="100%" height={250}><BarChart data={porResponsavel} layout="vertical" margin={{ left: 15, right: 15 }}><XAxis type="number" allowDecimals={false} tick={{ fontSize: 10, fill: dark ? "#9ca3af" : "#6b7280" }} axisLine={false} tickLine={false} /><YAxis type="category" dataKey="nome" width={105} tick={{ fontSize: 10, fill: dark ? "#d1d5db" : "#4b5563" }} axisLine={false} tickLine={false} /><Tooltip contentStyle={tooltip} /><Bar dataKey="total" fill="#2563eb" radius={[0, 4, 4, 0]} /></BarChart></ResponsiveContainer></div><div className="card p-5"><h2 className="mb-4 text-sm font-semibold text-gray-900">Assuntos mais frequentes</h2><ResponsiveContainer width="100%" height={250}><BarChart data={porAssunto} layout="vertical" margin={{ left: 15, right: 15 }}><XAxis type="number" allowDecimals={false} tick={{ fontSize: 10, fill: dark ? "#9ca3af" : "#6b7280" }} axisLine={false} tickLine={false} /><YAxis type="category" dataKey="nome" width={115} tick={{ fontSize: 10, fill: dark ? "#d1d5db" : "#4b5563" }} axisLine={false} tickLine={false} /><Tooltip contentStyle={tooltip} /><Bar dataKey="total" fill="#C41E23" radius={[0, 4, 4, 0]} /></BarChart></ResponsiveContainer></div><div className="card p-5"><h2 className="mb-4 text-sm font-semibold text-gray-900">Situação dos chamados</h2><ResponsiveContainer width="100%" height={205}><PieChart><Pie data={porSituacao} dataKey="total" nameKey="nome" innerRadius={48} outerRadius={76} paddingAngle={3}>{porSituacao.map((_, index) => <Cell key={index} fill={CORES[index % CORES.length]} />)}</Pie><Tooltip contentStyle={tooltip} /></PieChart></ResponsiveContainer><div className="space-y-1.5">{porSituacao.map((item, index) => <div key={item.nome} className="flex items-center justify-between text-[11px]"><span className="flex items-center gap-2 text-gray-500"><span className="h-2 w-2 rounded-full" style={{ background: CORES[index % CORES.length] }} />{item.nome}</span><strong className="text-gray-900">{item.total}</strong></div>)}</div></div></div>
    <section className="card overflow-hidden"><div className="flex items-center justify-between border-b border-gray-100 px-5 py-4"><h2 className="text-sm font-semibold text-gray-900">Chamados</h2><span className="text-xs text-gray-400">{cache ? "Dados em cache • " : ""}{dados.length} resultado(s)</span></div>{loading && !chamados.length ? <div className="flex items-center justify-center gap-2 p-12 text-sm text-gray-400"><Loader2 className="h-5 w-5 animate-spin" /> Consultando páginas do SULTS...</div> : <div className="overflow-x-auto"><table className="w-full min-w-[1050px] text-left"><thead className="bg-gray-50 text-[10px] uppercase tracking-wide text-gray-500"><tr><th className="px-5 py-3">Chamado</th><th className="px-4 py-3">Situação</th><th className="px-4 py-3">Responsável</th><th className="px-4 py-3">Assunto</th><th className="px-4 py-3">Apoios</th><th className="px-4 py-3">Aberto</th><th className="px-4 py-3">Interações</th></tr></thead><tbody>{dados.map((item) => <tr key={item.id} className="border-t border-gray-100 text-xs hover:bg-gray-50"><td className="px-5 py-3"><p className="font-semibold text-gray-900">#{item.id} — {item.titulo}</p><p className="mt-1 text-[10px] text-gray-400">{item.solicitante?.nome ?? "Solicitante não informado"} • {item.departamento?.nome ?? "Sem departamento"}</p></td><td className="px-4 py-3"><span className={`badge ${item.situacao === 1 ? "badge-warn" : [2, 3].includes(item.situacao) ? "badge-ok" : "badge-info"}`}>{SITUACOES[item.situacao] ?? item.situacao}</span></td><td className="px-4 py-3 font-medium text-gray-700">{item.responsavel?.nome ?? "Fila / sem responsável"}</td><td className="px-4 py-3 text-gray-600">{nomeAssunto(item)}</td><td className="px-4 py-3"><div className="flex items-center gap-1.5 text-gray-500"><UsersRound className="h-3.5 w-3.5" />{item.apoio?.map((registro) => registro.pessoa?.nome).filter(Boolean).join(", ") || "—"}</div></td><td className="px-4 py-3 text-gray-500">{data(item.aberto)}</td><td className="px-4 py-3 text-gray-500">{(item.countInteracaoPublico ?? 0) + (item.countInteracaoInterno ?? 0)}</td></tr>)}</tbody></table></div>}</section>
  </div>;
}
