import { useMemo, useState, type FormEvent } from "react";
import { AlertCircle, Bot, Check, CheckCircle2, CloudCog, Loader2, Search, UserRoundSearch } from "lucide-react";
import PlantaoConfiguracoes from "../components/configuracoes/PlantaoConfiguracoes";
import { buscarPessoaSultsServidor } from "../services/chamadosSults";
import { carregarConfiguracaoSults, salvarConfiguracaoSults, type ConfiguracaoSults } from "../services/sults";

type Feedback = { tipo: "sucesso" | "erro" | "info"; texto: string } | null;

export default function ConfiguracoesPage() {
  const inicial = useMemo(() => carregarConfiguracaoSults(), []);
  const [config, setConfig] = useState<ConfiguracaoSults>(inicial);
  const [carregando, setCarregando] = useState<"pessoa" | null>(null);
  const [feedback, setFeedback] = useState<Feedback>(null);

  const atualizar = <K extends keyof ConfiguracaoSults>(campo: K, valor: ConfiguracaoSults[K]) => setConfig((atual) => ({ ...atual, [campo]: valor }));
  const buscarPessoa = async () => { setCarregando("pessoa"); setFeedback(null); try { const pessoa = await buscarPessoaSultsServidor(config.login); setConfig((atual) => ({ ...atual, pessoaId: pessoa.id, pessoaNome: pessoa.nome })); setFeedback({ tipo: "sucesso", texto: `${pessoa.nome} localizado com o ID ${pessoa.id}.` }); } catch (erro) { setFeedback({ tipo: "erro", texto: erro instanceof Error ? erro.message : "Não foi possível localizar a pessoa." }); } finally { setCarregando(null); } };
  const salvar = (event: FormEvent) => { event.preventDefault(); if (!config.login.trim() || !config.pessoaId) { setFeedback({ tipo: "erro", texto: "Informe o Login SULTS e faça a consulta antes de salvar." }); return; } salvarConfiguracaoSults({ ...config, login: config.login.trim() }); setFeedback({ tipo: "sucesso", texto: "Login SULTS salvo neste navegador." }); };

  return <div className="page"><div className="page-header items-start"><div><h1 className="page-title">Configurações</h1><p className="page-subtitle">Configure o Login SULTS e as notificações do plantão.</p></div><span className="badge badge-ok flex items-center gap-1.5"><span className="h-1.5 w-1.5 rounded-full bg-green-500" /> Credencial protegida no servidor</span></div>
    <div className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_360px]"><form onSubmit={salvar} className="card overflow-hidden"><div className="flex items-center gap-3 border-b border-gray-100 px-6 py-5"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-brand-50"><Bot className="h-5 w-5 text-brand-600" /></div><div><h2 className="font-semibold text-gray-900">Integração SULTS</h2><p className="text-xs text-gray-500">Vinculação do login do analista</p></div></div>
      <div className="space-y-6 p-6"><div className="flex items-start gap-3 rounded-xl border border-blue-100 bg-blue-50 p-4"><CloudCog className="mt-0.5 h-5 w-5 shrink-0 text-blue-600" /><div><p className="text-sm font-medium text-blue-900">Autenticação configurada por variável de ambiente</p><p className="mt-1 text-xs leading-5 text-blue-700">O token SULTS é lido exclusivamente pelo servidor e não é exibido nem enviado ao navegador.</p></div></div>
        <section><div className="mb-3 flex items-center gap-2"><span className="flex h-6 w-6 items-center justify-center rounded-full bg-gray-900 text-xs font-semibold text-white">1</span><h3 className="text-sm font-semibold text-gray-900">Login SULTS</h3></div><label className="mb-1.5 block text-xs font-medium text-gray-600">Login ou nome completo usado no SULTS</label><div className="flex gap-2"><div className="relative flex-1"><UserRoundSearch className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-gray-400" /><input value={config.login} onChange={(event) => { atualizar("login", event.target.value); atualizar("pessoaId", null); atualizar("pessoaNome", ""); setFeedback(null); }} className="input pl-9" placeholder="Ex.: Adriano Santana" /></div><button type="button" onClick={buscarPessoa} disabled={carregando !== null || !config.login.trim()} className="btn-secondary flex items-center gap-2" title="Consultar login">{carregando === "pessoa" ? <Loader2 className="h-4 w-4 animate-spin" /> : <Search className="h-4 w-4" />}<span className="hidden sm:inline">{carregando === "pessoa" ? "Consultando..." : "Consultar"}</span></button></div>{config.pessoaNome && <div className="mt-3 flex items-center gap-2 rounded-lg bg-green-50 px-3 py-2 text-xs font-medium text-green-700"><Check className="h-3.5 w-3.5" /> Login confirmado: {config.pessoaNome}. ID {config.pessoaId} encontrado e salvo internamente.</div>}</section>
        {feedback && <div className={`flex items-start gap-2 rounded-xl px-4 py-3 text-sm ${feedback.tipo === "erro" ? "bg-red-50 text-red-700" : feedback.tipo === "sucesso" ? "bg-green-50 text-green-700" : "bg-blue-50 text-blue-700"}`}>{feedback.tipo === "erro" ? <AlertCircle className="mt-0.5 h-4 w-4 shrink-0" /> : <CheckCircle2 className="mt-0.5 h-4 w-4 shrink-0" />}{feedback.texto}</div>}
      </div><div className="flex justify-end border-t border-gray-100 bg-gray-50 px-6 py-4"><button type="submit" className="btn-primary">Salvar configuração</button></div></form>
      <aside className="space-y-4"><div className="card p-5"><h2 className="mb-4 text-sm font-semibold text-gray-900">Status da integração</h2><div className="space-y-3 text-xs"><div className="flex items-center justify-between gap-3"><span className="text-gray-500">Autenticação</span><span className="badge badge-ok">Servidor / .env</span></div><div className="flex items-center justify-between gap-3"><span className="text-gray-500">Localizar login</span><span className="badge badge-ok">Disponível</span></div><div className="flex items-center justify-between gap-3"><span className="text-gray-500">Criar chamado</span><span className="badge badge-ok">Disponível</span></div></div></div><div className="card p-5"><h2 className="mb-2 text-sm font-semibold text-gray-900">Como o login é confirmado?</h2><p className="text-xs leading-5 text-gray-500">A busca consulta os chamados dos últimos 180 dias e compara o nome com solicitantes, responsáveis e apoios. O ID encontrado é guardado internamente e usado para filtrar a Jornada TI.</p></div></aside></div>
    <div className="mt-6"><PlantaoConfiguracoes /></div>
  </div>;
}
