import { useMemo, useState, type FormEvent } from "react";
import { AlertCircle, Bot, Check, CheckCircle2, CloudCog, Loader2, MessageSquareText, Search, TicketCheck, UserRoundSearch } from "lucide-react";
import PlantaoConfiguracoes from "../components/configuracoes/PlantaoConfiguracoes";
import { buscarPessoaSultsServidor, listarChamadosNovosServidor } from "../services/chamadosSults";
import { carregarConfiguracaoSults, salvarConfiguracaoSults, type ConfiguracaoSults } from "../services/sults";

type Feedback = { tipo: "sucesso" | "erro" | "info"; texto: string } | null;

export default function ConfiguracoesPage() {
  const inicial = useMemo(() => carregarConfiguracaoSults(), []);
  const [config, setConfig] = useState<ConfiguracaoSults>(inicial);
  const [carregando, setCarregando] = useState<"pessoa" | "chamados" | null>(null);
  const [feedback, setFeedback] = useState<Feedback>(null);

  const atualizar = <K extends keyof ConfiguracaoSults>(campo: K, valor: ConfiguracaoSults[K]) => setConfig((atual) => ({ ...atual, [campo]: valor }));
  const buscarPessoa = async () => { setCarregando("pessoa"); setFeedback(null); try { const pessoa = await buscarPessoaSultsServidor(config.login); setConfig((atual) => ({ ...atual, pessoaId: pessoa.id, pessoaNome: pessoa.nome })); setFeedback({ tipo: "sucesso", texto: `${pessoa.nome} localizado com o ID ${pessoa.id}.` }); } catch (erro) { setFeedback({ tipo: "erro", texto: erro instanceof Error ? erro.message : "Não foi possível localizar a pessoa." }); } finally { setCarregando(null); } };
  const conferirChamados = async () => { setCarregando("chamados"); setFeedback(null); try { const chamados = await listarChamadosNovosServidor(config.pessoaId); setFeedback({ tipo: "info", texto: `${chamados.length} chamado(s) novo(s) encontrado(s)${config.pessoaId ? ` para o ID ${config.pessoaId}` : ""}.` }); } catch (erro) { setFeedback({ tipo: "erro", texto: erro instanceof Error ? erro.message : "Não foi possível consultar os chamados." }); } finally { setCarregando(null); } };
  const salvar = (event: FormEvent) => { event.preventDefault(); if (!config.login.trim() || !config.pessoaId || !config.mensagemPadrao.trim()) { setFeedback({ tipo: "erro", texto: "Preencha login, ID da pessoa e mensagem padrão." }); return; } salvarConfiguracaoSults({ ...config, login: config.login.trim(), mensagemPadrao: config.mensagemPadrao.trim() }); setFeedback({ tipo: "sucesso", texto: "Configuração do analista salva neste navegador." }); };

  return <div className="page"><div className="page-header items-start"><div><h1 className="page-title">Configurações</h1><p className="page-subtitle">Configure o analista, a resposta padrão e as notificações do plantão.</p></div><span className="badge badge-ok flex items-center gap-1.5"><span className="h-1.5 w-1.5 rounded-full bg-green-500" /> Credencial protegida no servidor</span></div>
    <div className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_360px]"><form onSubmit={salvar} className="card overflow-hidden"><div className="flex items-center gap-3 border-b border-gray-100 px-6 py-5"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-brand-50"><Bot className="h-5 w-5 text-brand-600" /></div><div><h2 className="font-semibold text-gray-900">Integração SULTS</h2><p className="text-xs text-gray-500">Identificação do analista e mensagem padrão</p></div></div>
      <div className="space-y-6 p-6"><div className="flex items-start gap-3 rounded-xl border border-blue-100 bg-blue-50 p-4"><CloudCog className="mt-0.5 h-5 w-5 shrink-0 text-blue-600" /><div><p className="text-sm font-medium text-blue-900">Autenticação configurada por variável de ambiente</p><p className="mt-1 text-xs leading-5 text-blue-700">O token SULTS é lido exclusivamente pelo servidor e não é exibido nem enviado ao navegador.</p></div></div>
        <section><div className="mb-3 flex items-center gap-2"><span className="flex h-6 w-6 items-center justify-center rounded-full bg-gray-900 text-xs font-semibold text-white">1</span><h3 className="text-sm font-semibold text-gray-900">Identificar o analista</h3></div><div className="grid gap-4 sm:grid-cols-[minmax(0,1fr)_160px]"><div><label className="mb-1.5 block text-xs font-medium text-gray-600">Login ou nome no SULTS</label><div className="flex gap-2"><div className="relative flex-1"><UserRoundSearch className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-gray-400" /><input value={config.login} onChange={(event) => { atualizar("login", event.target.value); atualizar("pessoaNome", ""); }} className="input pl-9" placeholder="Ex.: Adriano Santana" /></div><button type="button" onClick={buscarPessoa} disabled={carregando !== null} className="btn-secondary" title="Buscar ID">{carregando === "pessoa" ? <Loader2 className="h-4 w-4 animate-spin" /> : <Search className="h-4 w-4" />}</button></div></div><div><label className="mb-1.5 block text-xs font-medium text-gray-600">ID da pessoa</label><input type="number" min="1" value={config.pessoaId ?? ""} onChange={(event) => atualizar("pessoaId", event.target.value ? Number(event.target.value) : null)} className="input" placeholder="Ex.: 42" /></div></div>{config.pessoaNome && <div className="mt-3 flex items-center gap-2 rounded-lg bg-green-50 px-3 py-2 text-xs font-medium text-green-700"><Check className="h-3.5 w-3.5" /> {config.pessoaNome} vinculado ao ID {config.pessoaId}</div>}</section>
        <section className="border-t border-gray-100 pt-6"><div className="mb-3 flex items-center gap-2"><span className="flex h-6 w-6 items-center justify-center rounded-full bg-gray-900 text-xs font-semibold text-white">2</span><h3 className="text-sm font-semibold text-gray-900">Definir resposta padrão</h3></div><label className="mb-1.5 block text-xs font-medium text-gray-600">Mensagem enviada ao receber um chamado novo</label><div className="relative"><MessageSquareText className="absolute left-3 top-3 h-4 w-4 text-gray-400" /><textarea value={config.mensagemPadrao} onChange={(event) => atualizar("mensagemPadrao", event.target.value)} className="input min-h-32 resize-y pl-9" maxLength={2000} placeholder="Digite a mensagem padrão..." /><span className="absolute bottom-2.5 right-3 text-[10px] text-gray-400">{config.mensagemPadrao.length}/2000</span></div></section>
        {feedback && <div className={`flex items-start gap-2 rounded-xl px-4 py-3 text-sm ${feedback.tipo === "erro" ? "bg-red-50 text-red-700" : feedback.tipo === "sucesso" ? "bg-green-50 text-green-700" : "bg-blue-50 text-blue-700"}`}>{feedback.tipo === "erro" ? <AlertCircle className="mt-0.5 h-4 w-4 shrink-0" /> : <CheckCircle2 className="mt-0.5 h-4 w-4 shrink-0" />}{feedback.texto}</div>}
      </div><div className="flex flex-wrap items-center justify-between gap-3 border-t border-gray-100 bg-gray-50 px-6 py-4"><button type="button" onClick={conferirChamados} disabled={carregando !== null} className="btn-secondary flex items-center gap-2">{carregando === "chamados" ? <Loader2 className="h-4 w-4 animate-spin" /> : <TicketCheck className="h-4 w-4" />} Consultar chamados novos</button><button type="submit" className="btn-primary">Salvar configuração</button></div></form>
      <aside className="space-y-4"><div className="card p-5"><h2 className="mb-4 text-sm font-semibold text-gray-900">Status da integração</h2><div className="space-y-3 text-xs"><div className="flex items-center justify-between gap-3"><span className="text-gray-500">Autenticação</span><span className="badge badge-ok">Servidor / .env</span></div><div className="flex items-center justify-between gap-3"><span className="text-gray-500">Listar novos chamados</span><span className="badge badge-ok">Disponível</span></div><div className="flex items-center justify-between gap-3"><span className="text-gray-500">Localizar ID</span><span className="badge badge-ok">Disponível</span></div><div className="flex items-center justify-between gap-3"><span className="text-gray-500">Criar chamado</span><span className="badge badge-ok">Disponível</span></div><div className="flex items-center justify-between gap-3"><span className="text-gray-500">Responder chamado</span><span className="badge badge-warn">Aguardando API</span></div></div></div><div className="rounded-xl border border-amber-200 bg-amber-50 p-5"><div className="mb-2 flex items-center gap-2 text-sm font-semibold text-amber-900"><AlertCircle className="h-4 w-4" /> Sobre a resposta automática</div><p className="text-xs leading-5 text-amber-800">O endpoint informado cria um novo chamado; ele não responde um chamado existente. O envio automático deve permanecer desativado até a SULTS fornecer o endpoint de interação/resposta.</p></div><div className="card p-5"><h2 className="mb-2 text-sm font-semibold text-gray-900">Como o ID é encontrado?</h2><p className="text-xs leading-5 text-gray-500">A busca consulta os chamados pelo proxy protegido e compara o nome com solicitantes, responsáveis e apoios. Se o usuário não aparecer, o ID pode ser digitado manualmente.</p></div></aside></div>
    <div className="mt-6"><PlantaoConfiguracoes /></div>
  </div>;
}
