import { useEffect, useState } from "react";
import { Bar, BarChart, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { CircleCheck, CircleOff, MonitorCog, Pencil, Plus, Search, Trash2, TriangleAlert, X } from "lucide-react";
import DataLayoutSwitcher from "../components/ui/DataLayoutSwitcher";
import CrudModal from "../components/ui/CrudModal";
import { useDataLayout } from "../hooks/useDataLayout";
import { MAQUINAS, type MaquinaTI } from "../data/tiData";
import { useThemeContext } from "../hooks/ThemeContext";
import { excluirMaquina, listarMaquinas, salvarMaquina, type MaquinaRegistro } from "../services/cadastrosTi";

const MODELOS = [...new Set(MAQUINAS.map((item) => item.modelo))].sort();
const UNIDADES = [...new Set(MAQUINAS.map((item) => item.unidade))].sort();

function Status({ valor }: { valor: MaquinaTI["status"] }) {
  return <span className={`badge ${valor === "Online" ? "badge-ok" : valor === "Atenção" ? "badge-warn" : "badge-danger"}`}>{valor}</span>;
}

function Lista({ dados }: { dados: MaquinaTI[] }) {
  return <section className="card overflow-hidden"><div className="flex items-center justify-between border-b border-gray-100 px-5 py-4"><h2 className="flex items-center gap-2 text-sm font-semibold text-gray-900"><MonitorCog className="h-4 w-4 text-brand-600" /> Equipamentos</h2><span className="text-xs text-gray-400">{dados.length} resultado(s)</span></div><div className="divide-y divide-gray-100">{dados.map((item) => <article key={item.serie} className="grid gap-4 px-5 py-4 transition-colors hover:bg-gray-50 md:grid-cols-[minmax(220px,1.3fr)_minmax(190px,1fr)_minmax(190px,1fr)_120px]"><div><div className="flex items-center gap-2"><span className={`h-2 w-2 rounded-full ${item.status === "Online" ? "bg-green-500" : item.status === "Atenção" ? "bg-amber-500" : "bg-red-500"}`} /><h3 className="text-sm font-semibold text-gray-900">{item.maquina}</h3></div><p className="mt-1 pl-4 text-xs text-gray-500">{item.modelo} • Série {item.serie}</p></div><div><p className="text-[10px] uppercase tracking-wide text-gray-400">Unidade / Local</p><p className="mt-1 text-xs font-medium text-gray-700">{item.unidade} — {item.cidade}</p><p className="mt-1 text-[11px] text-gray-400">CNPJ {item.cnpj}</p></div><div><p className="text-[10px] uppercase tracking-wide text-gray-400">Rede / Contato</p><p className="mt-1 text-xs font-medium text-gray-700">IP {item.ip}</p><p className="mt-1 text-[11px] text-gray-400">{item.contato}</p></div><div className="md:text-right"><Status valor={item.status} />{item.observacao && <p className="mt-2 text-[10px] leading-4 text-gray-400">{item.observacao}</p>}</div></article>)}</div>{!dados.length && <p className="p-12 text-center text-sm text-gray-400">Nenhuma máquina encontrada.</p>}</section>;
}

function Cards({ dados }: { dados: MaquinaTI[] }) {
  return <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{dados.map((item) => <article key={item.serie} className="card p-5"><div className="flex items-start justify-between"><div className="flex h-11 w-11 items-center justify-center rounded-xl bg-brand-50"><MonitorCog className="h-5 w-5 text-brand-600" /></div><Status valor={item.status} /></div><h2 className="mt-4 text-sm font-semibold text-gray-900">{item.maquina}</h2><p className="mt-1 text-xs text-gray-500">{item.modelo}</p><div className="my-4 space-y-3 rounded-xl bg-gray-50 p-3 text-xs"><div className="flex justify-between gap-3"><span className="text-gray-400">Série</span><span className="font-mono font-medium text-gray-700">{item.serie}</span></div><div className="flex justify-between gap-3"><span className="text-gray-400">Unidade</span><span className="font-medium text-gray-700">{item.unidade}</span></div><div className="flex justify-between gap-3"><span className="text-gray-400">IP</span><span className="font-medium text-gray-700">{item.ip}</span></div></div><p className="text-xs font-medium text-gray-700">{item.cidade}</p><p className="mt-1 text-[11px] text-gray-400">{item.contato} • {item.cnpj}</p>{item.observacao && <p className="mt-4 border-t border-gray-100 pt-3 text-xs text-gray-500">{item.observacao}</p>}</article>)}</div>;
}

function Tabela({ dados }: { dados: MaquinaTI[] }) {
  return <section className="card overflow-hidden"><div className="flex items-center justify-between border-b border-gray-100 px-5 py-4"><h2 className="text-sm font-semibold text-gray-900">Inventário filtrado</h2><span className="text-xs text-gray-400">{dados.length} resultado(s)</span></div><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left"><thead className="bg-gray-50 text-[10px] uppercase tracking-wide text-gray-500"><tr><th className="px-5 py-3">Máquina</th><th className="px-4 py-3">Modelo</th><th className="px-4 py-3">Unidade</th><th className="px-4 py-3">Cidade</th><th className="px-4 py-3">IP</th><th className="px-4 py-3">Status</th></tr></thead><tbody>{dados.map((item) => <tr key={item.serie} className="border-t border-gray-100 text-xs hover:bg-gray-50"><td className="px-5 py-3"><p className="font-semibold text-gray-900">{item.maquina}</p><p className="mt-1 font-mono text-[10px] text-gray-400">{item.serie}</p></td><td className="px-4 py-3 text-gray-600">{item.modelo}</td><td className="px-4 py-3 font-medium text-gray-700">{item.unidade}</td><td className="px-4 py-3 text-gray-500">{item.cidade}</td><td className="px-4 py-3 font-mono text-gray-600">{item.ip}</td><td className="px-4 py-3"><Status valor={item.status} /></td></tr>)}</tbody></table></div></section>;
}

export default function MaquinasPage() {
  const { dark } = useThemeContext();
  const [layout, setLayout] = useDataLayout("maquinas", "list");
  const [registros, setRegistros] = useState<MaquinaRegistro[]>(() => MAQUINAS.map((item, index) => ({ ...item, id: `demo-maquina-${index}` })));
  const [edicao, setEdicao] = useState<MaquinaRegistro | null>(null); const [salvando, setSalvando] = useState(false); const [erroCrud, setErroCrud] = useState("");
  useEffect(() => { listarMaquinas().then(setRegistros).catch(() => undefined); }, []);
  const [busca, setBusca] = useState(""); const [modelo, setModelo] = useState("Todos"); const [unidade, setUnidade] = useState("Todos"); const [status, setStatus] = useState("Todos");
  const termo = busca.trim().toLocaleLowerCase("pt-BR");
  const dados = registros.filter((item) => { const texto = Object.values(item).join(" ").toLocaleLowerCase("pt-BR"); return (!termo || texto.includes(termo)) && (modelo === "Todos" || item.modelo === modelo) && (unidade === "Todos" || item.unidade === unidade) && (status === "Todos" || item.status === status); });
  const limpar = () => { setBusca(""); setModelo("Todos"); setUnidade("Todos"); setStatus("Todos"); };
  const online = dados.filter((item) => item.status === "Online").length; const atencao = dados.filter((item) => item.status === "Atenção").length; const offline = dados.filter((item) => item.status === "Offline").length;
  const porStatus = ["Online", "Atenção", "Offline"].map((nome) => ({ nome, total: dados.filter((item) => item.status === nome).length })).filter((item) => item.total);
  const porModelo = MODELOS.map((nome) => ({ nome: nome.length > 22 ? `${nome.slice(0, 22)}…` : nome, total: dados.filter((item) => item.modelo === nome).length })).filter((item) => item.total).sort((a, b) => b.total - a.total);
  const cores = ["#16a34a", "#d97706", "#dc2626"];
  const tooltip = { backgroundColor: dark ? "#111827" : "#fff", border: `1px solid ${dark ? "#374151" : "#e5e7eb"}`, borderRadius: 8, fontSize: 12 };

  const novo = () => setEdicao({ id: "", maquina: "", serie: "", modelo: "", unidade: "", contato: "", cnpj: "", cidade: "", ip: "—", status: "Online", observacao: "" });
  const salvar = async () => { if (!edicao) return; if (![edicao.maquina, edicao.serie, edicao.modelo, edicao.unidade, edicao.cidade].every((valor) => valor.trim())) { setErroCrud("Preencha máquina, série, modelo, unidade e cidade."); return; } setSalvando(true); setErroCrud(""); try { setRegistros(await salvarMaquina(edicao)); setEdicao(null); } catch (erro) { setErroCrud(erro instanceof Error ? erro.message : "Erro ao salvar."); } finally { setSalvando(false); } };
  const excluir = async (item: MaquinaRegistro) => { if (!window.confirm(`Excluir ${item.maquina}?`)) return; try { setRegistros(await excluirMaquina(item)); } catch (erro) { window.alert(erro instanceof Error ? erro.message : "Erro ao excluir."); } };
  return <div className="page"><div className="page-header gap-4"><div><h1 className="page-title">Máquinas e unidades</h1><p className="page-subtitle">Inventário de impressoras e equipamentos das lojas.</p></div><div className="flex items-center gap-2"><button type="button" onClick={novo} className="btn-primary flex items-center gap-2 text-sm"><Plus className="h-4 w-4" /> Nova máquina</button><DataLayoutSwitcher value={layout} onChange={setLayout} /></div></div>
    <div className="card mb-5 p-4"><div className="grid grid-cols-1 gap-3 sm:grid-cols-2 xl:grid-cols-6"><label className="relative sm:col-span-2"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-gray-400" /><input className="input pl-9" value={busca} onChange={(e) => setBusca(e.target.value)} placeholder="Buscar máquina, série, CNPJ, cidade, IP ou observação..." /></label><select className="input" value={modelo} onChange={(e) => setModelo(e.target.value)}><option>Todos</option>{MODELOS.map((item) => <option key={item}>{item}</option>)}</select><select className="input" value={unidade} onChange={(e) => setUnidade(e.target.value)}><option>Todos</option>{UNIDADES.map((item) => <option key={item}>{item}</option>)}</select><select className="input" value={status} onChange={(e) => setStatus(e.target.value)}><option>Todos</option><option>Online</option><option>Atenção</option><option>Offline</option></select><button type="button" onClick={limpar} className="btn-secondary flex w-full items-center justify-center gap-2"><X className="h-4 w-4" /> Limpar</button></div></div>

    {layout === "dashboard" && <div className="space-y-5"><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[
      { label: "Equipamentos filtrados", value: dados.length, icon: MonitorCog, color: "bg-blue-50 text-blue-600" },
      { label: "Online", value: online, icon: CircleCheck, color: "bg-green-50 text-green-600" },
      { label: "Precisam de atenção", value: atencao, icon: TriangleAlert, color: "bg-amber-50 text-amber-600" },
      { label: "Offline", value: offline, icon: CircleOff, color: "bg-red-50 text-red-600" },
    ].map(({ label, value, icon: Icon, color }) => <div key={label} className="card flex items-center gap-4 p-4"><div className={`flex h-11 w-11 items-center justify-center rounded-xl ${color}`}><Icon className="h-5 w-5" /></div><div><p className="text-xs text-gray-500">{label}</p><p className="mt-1 text-xl font-semibold text-gray-900">{value}</p></div></div>)}</div>
      <div className="grid gap-5 lg:grid-cols-3"><div className="card p-5 lg:col-span-2"><h2 className="mb-4 text-sm font-semibold text-gray-900">Equipamentos por modelo</h2><ResponsiveContainer width="100%" height={230}><BarChart data={porModelo} layout="vertical" margin={{ left: 20, right: 20 }}><XAxis type="number" allowDecimals={false} tick={{ fill: dark ? "#9ca3af" : "#6b7280", fontSize: 10 }} axisLine={false} tickLine={false} /><YAxis type="category" dataKey="nome" width={150} tick={{ fill: dark ? "#d1d5db" : "#4b5563", fontSize: 10 }} axisLine={false} tickLine={false} /><Tooltip contentStyle={tooltip} /><Bar dataKey="total" name="Equipamentos" fill="#2563eb" radius={[0, 4, 4, 0]} /></BarChart></ResponsiveContainer></div><div className="card p-5"><h2 className="mb-4 text-sm font-semibold text-gray-900">Disponibilidade</h2><ResponsiveContainer width="100%" height={190}><PieChart><Pie data={porStatus} dataKey="total" nameKey="nome" innerRadius={45} outerRadius={70} paddingAngle={3}>{porStatus.map((_, index) => <Cell key={index} fill={cores[index]} />)}</Pie><Tooltip contentStyle={tooltip} /></PieChart></ResponsiveContainer><div className="space-y-2">{porStatus.map((item, index) => <div key={item.nome} className="flex items-center justify-between text-xs"><span className="flex items-center gap-2 text-gray-500"><span className="h-2 w-2 rounded-full" style={{ background: cores[index] }} />{item.nome}</span><strong className="text-gray-900">{item.total}</strong></div>)}</div></div></div><Tabela dados={dados} /></div>}
    {layout === "cards" && <Cards dados={dados} />}
    {layout === "list" && <Lista dados={dados} />}
    <section className="card mt-5 overflow-hidden"><div className="flex items-center justify-between border-b border-gray-100 px-5 py-4"><h2 className="text-sm font-semibold text-gray-900">Gerenciar equipamentos</h2><span className="text-xs text-gray-400">Editar ou excluir</span></div><div className="divide-y divide-gray-100">{dados.map((item) => <div key={item.id} className="flex items-center gap-4 px-5 py-3"><div className="min-w-0 flex-1"><p className="truncate text-xs font-semibold text-gray-900">{item.maquina}</p><p className="mt-1 text-[10px] text-gray-400">{item.serie} • {item.unidade}</p></div><button type="button" onClick={() => setEdicao(item)} className="rounded-lg p-2 text-gray-400 hover:bg-blue-50 hover:text-blue-600"><Pencil className="h-4 w-4" /></button><button type="button" onClick={() => excluir(item)} className="rounded-lg p-2 text-gray-400 hover:bg-red-50 hover:text-red-600"><Trash2 className="h-4 w-4" /></button></div>)}</div></section>
    {edicao && <CrudModal titulo={edicao.id ? "Editar máquina" : "Nova máquina"} salvando={salvando} erro={erroCrud} onClose={() => setEdicao(null)} onSave={salvar}><div className="grid gap-4 sm:grid-cols-2">{[["Máquina", "maquina"], ["Número de série", "serie"], ["Modelo", "modelo"], ["Unidade", "unidade"], ["Cidade/UF", "cidade"], ["Contato", "contato"], ["CNPJ", "cnpj"], ["IP", "ip"], ["Observação", "observacao"]].map(([label, campo]) => <label key={campo} className={campo === "observacao" ? "sm:col-span-2" : ""}><span className="mb-1.5 block text-xs font-medium text-gray-600">{label}</span><input className="input" value={String(edicao[campo as keyof MaquinaRegistro])} onChange={(e) => setEdicao((atual) => atual ? { ...atual, [campo]: e.target.value } : atual)} /></label>)}<label><span className="mb-1.5 block text-xs font-medium text-gray-600">Status</span><select className="input" value={edicao.status} onChange={(e) => setEdicao({ ...edicao, status: e.target.value as MaquinaTI["status"] })}><option>Online</option><option>Atenção</option><option>Offline</option></select></label></div></CrudModal>}
  </div>;
}
