import { useState } from "react";
import { MonitorCog, Search, X } from "lucide-react";
import { MAQUINAS } from "../data/tiData";

export default function MaquinasPage() {
  const [busca, setBusca] = useState(""); const [modelo, setModelo] = useState("Todos"); const [unidade, setUnidade] = useState("Todos"); const [status, setStatus] = useState("Todos");
  const modelos = [...new Set(MAQUINAS.map((item) => item.modelo))].sort(); const unidades = [...new Set(MAQUINAS.map((item) => item.unidade))].sort();
  const dados = MAQUINAS.filter((item) => { const termo = busca.trim().toLocaleLowerCase("pt-BR"); const texto = Object.values(item).join(" ").toLocaleLowerCase("pt-BR"); return (!termo || texto.includes(termo)) && (modelo === "Todos" || item.modelo === modelo) && (unidade === "Todos" || item.unidade === unidade) && (status === "Todos" || item.status === status); });
  const limpar = () => { setBusca(""); setModelo("Todos"); setUnidade("Todos"); setStatus("Todos"); };
  return <div className="page"><div className="page-header"><div><h1 className="page-title">Máquinas e unidades</h1><p className="page-subtitle">Inventário completo de impressoras e equipamentos das lojas.</p></div><span className="badge badge-info">Layout lista</span></div>
    <div className="card mb-5 p-4"><div className="grid gap-3 lg:grid-cols-[minmax(260px,1fr)_repeat(3,200px)_auto]"><label className="relative"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-gray-400" /><input className="input pl-9" value={busca} onChange={(e) => setBusca(e.target.value)} placeholder="Buscar máquina, série, CNPJ, cidade, IP ou observação..." /></label><select className="input" value={modelo} onChange={(e) => setModelo(e.target.value)}><option>Todos</option>{modelos.map((item) => <option key={item}>{item}</option>)}</select><select className="input" value={unidade} onChange={(e) => setUnidade(e.target.value)}><option>Todos</option>{unidades.map((item) => <option key={item}>{item}</option>)}</select><select className="input" value={status} onChange={(e) => setStatus(e.target.value)}><option>Todos</option><option>Online</option><option>Atenção</option><option>Offline</option></select><button type="button" onClick={limpar} className="btn-secondary flex items-center justify-center gap-2"><X className="h-4 w-4" /> Limpar</button></div></div>
    <section className="card overflow-hidden"><div className="flex items-center justify-between border-b border-gray-100 px-5 py-4"><h2 className="flex items-center gap-2 text-sm font-semibold text-gray-900"><MonitorCog className="h-4 w-4 text-brand-600" /> Equipamentos</h2><span className="text-xs text-gray-400">{dados.length} resultado(s)</span></div><div className="divide-y divide-gray-100">{dados.map((item) => <article key={item.serie} className="grid gap-4 px-5 py-4 transition-colors hover:bg-gray-50 md:grid-cols-[minmax(220px,1.3fr)_minmax(190px,1fr)_minmax(190px,1fr)_120px]">
      <div><div className="flex items-center gap-2"><span className={`h-2 w-2 rounded-full ${item.status === "Online" ? "bg-green-500" : item.status === "Atenção" ? "bg-amber-500" : "bg-red-500"}`} /><h3 className="text-sm font-semibold text-gray-900">{item.maquina}</h3></div><p className="mt-1 pl-4 text-xs text-gray-500">{item.modelo} • Série {item.serie}</p></div>
      <div><p className="text-[10px] uppercase tracking-wide text-gray-400">Unidade / Local</p><p className="mt-1 text-xs font-medium text-gray-700">{item.unidade} — {item.cidade}</p><p className="mt-1 text-[11px] text-gray-400">CNPJ {item.cnpj}</p></div>
      <div><p className="text-[10px] uppercase tracking-wide text-gray-400">Rede / Contato</p><p className="mt-1 text-xs font-medium text-gray-700">IP {item.ip}</p><p className="mt-1 text-[11px] text-gray-400">{item.contato}</p></div>
      <div className="md:text-right"><span className={`badge ${item.status === "Online" ? "badge-ok" : item.status === "Atenção" ? "badge-warn" : "badge-danger"}`}>{item.status}</span>{item.observacao && <p className="mt-2 text-[10px] leading-4 text-gray-400">{item.observacao}</p>}</div>
    </article>)}</div>{dados.length === 0 && <p className="p-12 text-center text-sm text-gray-400">Nenhuma máquina encontrada.</p>}</section>
  </div>;
}
