import { useEffect, useMemo, useState } from "react";
import { CalendarCheck2, CalendarDays, Clock3, Mail, Pencil, Phone, Plus, Search, Trash2, UserRoundCheck, UsersRound, X } from "lucide-react";
import CrudModal from "../components/ui/CrudModal";
import { useConfirmDialog } from "../hooks/useConfirmDialog";
import DataLayoutSwitcher from "../components/ui/DataLayoutSwitcher";
import { useDataLayout } from "../hooks/useDataLayout";
import { excluirPlantao, listarPlantoes, materializarPlantoes, salvarPlantao } from "../services/plantao";
import type { PlantaoTI } from "../types/database";

const EQUIPE = [
  { nome: "Adriano Santana", email: "adriano.santana@fastdrywall.com.br", telefone: "(21) 99901-1001" },
  { nome: "Bruno Tamer", email: "bruno.tamer@fastdrywall.com.br", telefone: "(21) 99902-1002" },
  { nome: "Elaine Dias", email: "elaine.dias@fastdrywall.com.br", telefone: "(21) 99903-1003" },
  { nome: "Gleisly Santella", email: "gleisly.santella@fastdrywall.com.br", telefone: "(21) 99904-1004" },
];

function dataISO(data: Date) { return `${data.getFullYear()}-${String(data.getMonth() + 1).padStart(2, "0")}-${String(data.getDate()).padStart(2, "0")}`; }
function gerarEscala(): PlantaoTI[] { const hoje = new Date(); hoje.setHours(12, 0, 0, 0); const primeiro = new Date(hoje); primeiro.setDate(hoje.getDate() + ((6 - hoje.getDay() + 7) % 7)); return Array.from({ length: 10 }, (_, index) => { const data = new Date(primeiro); data.setDate(primeiro.getDate() + index * 7); const pessoa = EQUIPE[index % EQUIPE.length]; return { id: `demo-${index}`, data: dataISO(data), colaborador_nome: pessoa.nome, colaborador_email: pessoa.email, telefone: pessoa.telefone, observacao: index === 0 ? "Plantão remoto das 8h às 13h" : "Disponibilidade remota", created_at: new Date().toISOString(), created_by: null }; }); }
function formatarData(valor: string) { return new Date(`${valor}T12:00:00`).toLocaleDateString("pt-BR", { weekday: "long", day: "2-digit", month: "long" }); }
function iniciais(nome: string) { return nome.split(" ").slice(0, 2).map((parte) => parte[0]).join(""); }

function Acoes({ item, onEdit, onDelete }: { item: PlantaoTI; onEdit: (item: PlantaoTI) => void; onDelete: (item: PlantaoTI) => void }) { return <div className="flex justify-end gap-1"><button type="button" onClick={() => onEdit(item)} className="rounded-lg p-2 text-gray-400 hover:bg-blue-50 hover:text-blue-600" title="Editar"><Pencil className="h-4 w-4" /></button><button type="button" onClick={() => onDelete(item)} className="rounded-lg p-2 text-gray-400 hover:bg-red-50 hover:text-red-600" title="Excluir"><Trash2 className="h-4 w-4" /></button></div>; }
function Situacao({ item, hoje, proximo }: { item: PlantaoTI; hoje: string; proximo?: PlantaoTI }) { return <span className={`badge ${item.data >= hoje ? "badge-info" : "bg-gray-100 text-gray-500"}`}>{item.id === proximo?.id ? "Próximo" : item.data >= hoje ? "Agendado" : "Realizado"}</span>; }

function Lista({ dados, hoje, proximo, onEdit, onDelete }: { dados: PlantaoTI[]; hoje: string; proximo?: PlantaoTI; onEdit: (item: PlantaoTI) => void; onDelete: (item: PlantaoTI) => void }) {
  return <section className="card overflow-hidden"><div className="flex items-center justify-between border-b border-gray-100 px-5 py-4"><h2 className="text-sm font-semibold text-gray-900">Escala completa</h2><span className="text-xs text-gray-400">{dados.length} plantão(ões)</span></div><div className="divide-y divide-gray-100">{dados.map((item) => <article key={item.id} className="grid items-center gap-4 px-5 py-4 hover:bg-gray-50 md:grid-cols-[180px_minmax(220px,1fr)_minmax(220px,1fr)_110px_90px]"><div><p className="text-xs font-semibold capitalize text-gray-900">{formatarData(item.data)}</p><p className="mt-1 text-[10px] text-gray-400">{new Date(`${item.data}T12:00:00`).toLocaleDateString("pt-BR")}</p></div><div><p className="text-sm font-medium text-gray-900">{item.colaborador_nome}</p><p className="mt-1 text-xs text-gray-400">{item.colaborador_email}</p></div><div><p className="text-xs text-gray-600">{item.observacao || "Plantão remoto"}</p><p className="mt-1 text-[11px] text-gray-400">{item.telefone || "Sem telefone"}</p></div><Situacao item={item} hoje={hoje} proximo={proximo} /><Acoes item={item} onEdit={onEdit} onDelete={onDelete} /></article>)}</div>{!dados.length && <p className="p-10 text-center text-sm text-gray-400">Nenhum plantão encontrado.</p>}</section>;
}

function Cards({ dados, hoje, proximo, onEdit, onDelete }: { dados: PlantaoTI[]; hoje: string; proximo?: PlantaoTI; onEdit: (item: PlantaoTI) => void; onDelete: (item: PlantaoTI) => void }) {
  return <div className="grid gap-4 md:grid-cols-2 2xl:grid-cols-3">{dados.map((item) => <article key={item.id} className="card p-5"><div className="flex items-start justify-between gap-3"><div className="flex h-11 w-11 items-center justify-center rounded-xl bg-brand-50 font-semibold text-brand-600">{iniciais(item.colaborador_nome)}</div><div className="flex items-start gap-1"><Situacao item={item} hoje={hoje} proximo={proximo} /><Acoes item={item} onEdit={onEdit} onDelete={onDelete} /></div></div><h2 className="mt-4 text-sm font-semibold text-gray-900">{item.colaborador_nome}</h2><p className="mt-1 capitalize text-xs text-gray-500">{formatarData(item.data)}</p><div className="mt-4 space-y-2 rounded-xl bg-gray-50 p-3 text-xs text-gray-600"><p className="flex items-center gap-2"><Mail className="h-3.5 w-3.5 text-gray-400" /> {item.colaborador_email}</p><p className="flex items-center gap-2"><Phone className="h-3.5 w-3.5 text-gray-400" /> {item.telefone || "Sem telefone"}</p></div><p className="mt-4 text-xs leading-5 text-gray-500">{item.observacao || "Sem observação"}</p></article>)}{!dados.length && <div className="card p-12 text-center text-sm text-gray-400 md:col-span-2 2xl:col-span-3">Nenhum plantão encontrado.</div>}</div>;
}

export default function PlantaoPage() {
  const confirmar = useConfirmDialog();
  const demos = useMemo(() => gerarEscala(), []);
  const [layout, setLayout] = useDataLayout("plantao", "dashboard");
  const [plantoes, setPlantoes] = useState<PlantaoTI[]>(demos); const [origemDemo, setOrigemDemo] = useState(true);
  const [busca, setBusca] = useState(""); const [periodo, setPeriodo] = useState("Próximos");
  const [edicao, setEdicao] = useState<PlantaoTI | null>(null); const [salvando, setSalvando] = useState(false); const [erroCrud, setErroCrud] = useState("");
  useEffect(() => { listarPlantoes().then((dados) => { if (dados.length) { setPlantoes(dados); setOrigemDemo(false); } }).catch(() => undefined); }, []);
  const hoje = dataISO(new Date());
  const dados = useMemo(() => plantoes.filter((item) => { const termo = busca.trim().toLocaleLowerCase("pt-BR"); const texto = Object.values(item).join(" ").toLocaleLowerCase("pt-BR"); const periodoOk = periodo === "Todos" || (periodo === "Próximos" ? item.data >= hoje : item.data < hoje); return (!termo || texto.includes(termo)) && periodoOk; }), [plantoes, busca, periodo, hoje]);
  const proximo = [...plantoes].sort((a, b) => a.data.localeCompare(b.data)).find((item) => item.data >= hoje);
  const abrirNovo = () => setEdicao({ id: "", data: "", colaborador_nome: "", colaborador_email: "", telefone: "", observacao: "Plantão remoto das 8h às 13h", created_at: "", created_by: null });
  const preparar = async () => { if (!origemDemo) return plantoes; const reais = await materializarPlantoes(plantoes); setPlantoes(reais); setOrigemDemo(false); return reais; };
  const editar = async (item: PlantaoTI) => { setErroCrud(""); try { const base = await preparar(); setEdicao(base.find((registro) => registro.data === item.data) ?? item); } catch (erro) { window.alert(erro instanceof Error ? erro.message : "Erro ao preparar a escala."); } };
  const salvar = async () => { if (!edicao) return; if (!edicao.data || !edicao.colaborador_nome.trim() || !edicao.colaborador_email.trim()) { setErroCrud("Preencha a data, o nome e o e-mail do colaborador."); return; } if (new Date(`${edicao.data}T12:00:00`).getDay() !== 6) { setErroCrud("A data do plantão precisa ser um sábado."); return; } setSalvando(true); setErroCrud(""); try { let item = edicao; if (origemDemo) { const base = await preparar(); if (edicao.id.startsWith("demo-")) item = base.find((registro) => registro.data === edicao.data) ?? edicao; } await salvarPlantao({ id: item.id, data: edicao.data, colaborador_nome: edicao.colaborador_nome.trim(), colaborador_email: edicao.colaborador_email.trim(), telefone: edicao.telefone?.trim() || null, observacao: edicao.observacao?.trim() || null }); setPlantoes(await listarPlantoes()); setOrigemDemo(false); setEdicao(null); } catch (erro) { setErroCrud(erro instanceof Error ? erro.message : "Não foi possível salvar o plantão."); } finally { setSalvando(false); } };
  const excluir = async (item: PlantaoTI) => {
    const data = new Date(`${item.data}T12:00:00`).toLocaleDateString("pt-BR");
    await confirmar({
      titulo: "Excluir plantão?",
      descricao: "Essa ação remove o registro da escala e não poderá ser desfeita.",
      detalhe: `${item.colaborador_nome} • ${data}`,
      onConfirm: async () => {
        const base = await preparar();
        const real = base.find((registro) => registro.data === item.data);
        if (!real) throw new Error("Plantão não encontrado.");
        await excluirPlantao(real.id);
        setPlantoes(await listarPlantoes());
        setOrigemDemo(false);
      },
    });
  };
  const pessoas = new Set(dados.map((item) => item.colaborador_email)).size;

  return <div className="page"><div className="page-header gap-4"><div><h1 className="page-title">Plantão de sábado</h1><p className="page-subtitle">Visualize quem estará disponível e acompanhe a escala semanal.</p></div><div className="flex flex-wrap items-center gap-2">{origemDemo && <span className="badge badge-warn">Escala demonstrativa</span>}<button type="button" onClick={abrirNovo} className="btn-primary flex items-center gap-2 text-sm"><Plus className="h-4 w-4" /> Novo plantão</button><DataLayoutSwitcher value={layout} onChange={setLayout} /></div></div>
    <div className="card mb-5 p-4"><div className="grid grid-cols-1 gap-3 sm:grid-cols-2 xl:grid-cols-6"><label className="relative sm:col-span-4"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-gray-400" /><input className="input pl-9" value={busca} onChange={(e) => setBusca(e.target.value)} placeholder="Buscar por colaborador, e-mail, telefone, data ou observação..." /></label><select className="input" value={periodo} onChange={(e) => setPeriodo(e.target.value)}><option>Próximos</option><option>Realizados</option><option>Todos</option></select><button type="button" onClick={() => { setBusca(""); setPeriodo("Próximos"); }} className="btn-secondary flex w-full items-center justify-center gap-2"><X className="h-4 w-4" /> Limpar</button></div></div>
    {layout === "dashboard" && <div className="space-y-5">{proximo && <section className="overflow-hidden rounded-2xl bg-gray-900 text-white shadow-sm"><div className="grid xl:grid-cols-[1fr_420px]"><div className="p-7"><p className="mb-5 flex items-center gap-2 text-xs font-medium uppercase tracking-widest text-gray-400"><UserRoundCheck className="h-4 w-4 text-green-400" /> Próximo plantonista</p><div className="flex flex-col gap-5 sm:flex-row sm:items-center"><div className="flex h-16 w-16 items-center justify-center rounded-2xl bg-brand-600 text-xl font-semibold">{iniciais(proximo.colaborador_nome)}</div><div><h2 className="text-2xl font-semibold">{proximo.colaborador_nome}</h2><p className="mt-1 capitalize text-gray-300">{formatarData(proximo.data)}</p></div></div><div className="mt-6 flex flex-wrap gap-4 text-xs text-gray-300"><span className="flex items-center gap-2"><Mail className="h-4 w-4 text-gray-500" /> {proximo.colaborador_email}</span><span className="flex items-center gap-2"><Phone className="h-4 w-4 text-gray-500" /> {proximo.telefone}</span></div></div><div className="border-t border-white/10 bg-white/5 p-7 xl:border-l xl:border-t-0"><p className="text-xs uppercase tracking-wide text-gray-400">Informações do plantão</p><div className="mt-5 space-y-4 text-sm"><p className="flex items-center gap-3"><CalendarDays className="h-4 w-4 text-brand-400" /> Sábado, {new Date(`${proximo.data}T12:00:00`).toLocaleDateString("pt-BR")}</p><p className="flex items-center gap-3"><Clock3 className="h-4 w-4 text-brand-400" /> 08:00 às 13:00</p><p className="text-xs leading-5 text-gray-400">{proximo.observacao}</p></div></div></div></section>}<div className="grid gap-3 sm:grid-cols-3">{[{ label: "Plantões filtrados", valor: dados.length, icon: CalendarCheck2, cor: "bg-blue-50 text-blue-600" }, { label: "Próximos sábados", valor: dados.filter((item) => item.data >= hoje).length, icon: CalendarDays, cor: "bg-green-50 text-green-600" }, { label: "Plantonistas", valor: pessoas, icon: UsersRound, cor: "bg-violet-50 text-violet-600" }].map(({ label, valor, icon: Icon, cor }) => <div key={label} className="card flex items-center gap-4 p-4"><div className={`flex h-11 w-11 items-center justify-center rounded-xl ${cor}`}><Icon className="h-5 w-5" /></div><div><p className="text-xs text-gray-500">{label}</p><p className="mt-1 text-xl font-semibold text-gray-900">{valor}</p></div></div>)}</div><Lista dados={dados} hoje={hoje} proximo={proximo} onEdit={editar} onDelete={excluir} /></div>}
    {layout === "cards" && <Cards dados={dados} hoje={hoje} proximo={proximo} onEdit={editar} onDelete={excluir} />}
    {layout === "list" && <Lista dados={dados} hoje={hoje} proximo={proximo} onEdit={editar} onDelete={excluir} />}
    {edicao && <CrudModal titulo={edicao.id ? "Editar plantão" : "Novo plantão"} descricao="A escala aceita somente datas de sábado." salvando={salvando} erro={erroCrud} onClose={() => setEdicao(null)} onSave={salvar}><div className="grid gap-4 sm:grid-cols-2"><label><span className="mb-1.5 block text-xs font-medium text-gray-600">Data (sábado) *</span><input type="date" className="input" value={edicao.data} onChange={(e) => setEdicao({ ...edicao, data: e.target.value })} /></label><label><span className="mb-1.5 block text-xs font-medium text-gray-600">Colaborador *</span><input className="input" value={edicao.colaborador_nome} onChange={(e) => setEdicao({ ...edicao, colaborador_nome: e.target.value })} /></label><label><span className="mb-1.5 block text-xs font-medium text-gray-600">E-mail *</span><input type="email" className="input" value={edicao.colaborador_email} onChange={(e) => setEdicao({ ...edicao, colaborador_email: e.target.value })} /></label><label><span className="mb-1.5 block text-xs font-medium text-gray-600">Telefone</span><input className="input" value={edicao.telefone ?? ""} onChange={(e) => setEdicao({ ...edicao, telefone: e.target.value })} /></label><label className="sm:col-span-2"><span className="mb-1.5 block text-xs font-medium text-gray-600">Observação</span><textarea className="input min-h-24 resize-y" value={edicao.observacao ?? ""} onChange={(e) => setEdicao({ ...edicao, observacao: e.target.value })} /></label></div></CrudModal>}
  </div>;
}
