import { useEffect, useMemo, useState } from "react";
import { Activity, Pencil, Plus, Router, Search, ShieldCheck, Trash2, Wifi, WifiOff, X } from "lucide-react";
import CrudModal from "../components/ui/CrudModal";
import DataLayoutSwitcher from "../components/ui/DataLayoutSwitcher";
import { PROVEDORES, type ProvedorTI } from "../data/tiData";
import { useDataLayout } from "../hooks/useDataLayout";
import { excluirProvedor, listarProvedores, salvarProvedor, type ProvedorRegistro } from "../services/cadastrosTi";
import { listarFornecedores, type Fornecedor } from "../services/fornecedores";

function Status({ valor }: { valor: ProvedorTI["status"] }) {
  return <span className={`badge ${valor === "Operacional" ? "badge-ok" : valor === "Instável" ? "badge-warn" : "badge-danger"}`}>{valor}</span>;
}

function Acoes({ item, onEdit, onDelete }: { item: ProvedorRegistro; onEdit: (item: ProvedorRegistro) => void; onDelete: (item: ProvedorRegistro) => void }) {
  return <div className="flex justify-end gap-1"><button type="button" onClick={() => onEdit(item)} className="rounded-lg p-2 text-gray-400 hover:bg-blue-50 hover:text-blue-600" title="Editar"><Pencil className="h-4 w-4" /></button><button type="button" onClick={() => onDelete(item)} className="rounded-lg p-2 text-gray-400 hover:bg-red-50 hover:text-red-600" title="Excluir"><Trash2 className="h-4 w-4" /></button></div>;
}

function Tabela({ dados, onEdit, onDelete }: { dados: ProvedorRegistro[]; onEdit: (item: ProvedorRegistro) => void; onDelete: (item: ProvedorRegistro) => void }) {
  return <section className="card overflow-hidden"><div className="flex items-center justify-between border-b border-gray-100 px-5 py-4"><h2 className="text-sm font-semibold text-gray-900">Links por loja</h2><span className="text-xs text-gray-400">{dados.length} resultado(s)</span></div><div className="overflow-x-auto"><table className="w-full min-w-[1050px] text-left"><thead className="bg-gray-50 text-[10px] uppercase tracking-wide text-gray-500"><tr><th className="px-5 py-3">Loja</th><th className="px-4 py-3">Cidade/UF</th><th className="px-4 py-3">Principal</th><th className="px-4 py-3">Backup</th><th className="px-4 py-3">Velocidade</th><th className="px-4 py-3">Tecnologia</th><th className="px-4 py-3">Suporte</th><th className="px-4 py-3">Status</th><th className="px-4 py-3" /></tr></thead><tbody>{dados.map((item) => <tr key={item.id} className="border-t border-gray-100 text-xs hover:bg-gray-50"><td className="px-5 py-3 font-semibold text-gray-900">{item.loja}</td><td className="px-4 py-3 text-gray-600">{item.cidade}/{item.uf}</td><td className="px-4 py-3 font-medium text-gray-700">{item.provedorPrincipal}</td><td className="px-4 py-3 text-gray-600">{item.provedorBackup || "—"}</td><td className="px-4 py-3 text-gray-600">{item.velocidade}</td><td className="px-4 py-3 text-gray-600">{item.tecnologia}</td><td className="px-4 py-3 text-gray-600">{item.telefoneSuporte || "—"}</td><td className="px-4 py-3"><Status valor={item.status} /></td><td className="px-4 py-3"><Acoes item={item} onEdit={onEdit} onDelete={onDelete} /></td></tr>)}</tbody></table></div>{!dados.length && <p className="p-10 text-center text-sm text-gray-400">Nenhum provedor encontrado.</p>}</section>;
}

function Cards({ dados, onEdit, onDelete }: { dados: ProvedorRegistro[]; onEdit: (item: ProvedorRegistro) => void; onDelete: (item: ProvedorRegistro) => void }) {
  return <div className="grid gap-4 md:grid-cols-2 2xl:grid-cols-3">{dados.map((item) => <article key={item.id} className="card p-5"><div className="flex items-start justify-between gap-4"><div className="flex gap-3"><div className={`flex h-10 w-10 items-center justify-center rounded-xl ${item.status === "Operacional" ? "bg-green-50 text-green-600" : item.status === "Instável" ? "bg-amber-50 text-amber-600" : "bg-red-50 text-red-600"}`}>{item.status === "Indisponível" ? <WifiOff className="h-5 w-5" /> : <Wifi className="h-5 w-5" />}</div><div><h2 className="text-sm font-semibold text-gray-900">{item.loja}</h2><p className="mt-1 text-xs text-gray-400">{item.cidade}/{item.uf}</p></div></div><div className="flex items-start gap-1"><Status valor={item.status} /><Acoes item={item} onEdit={onEdit} onDelete={onDelete} /></div></div><div className="mt-5 grid grid-cols-2 gap-4 border-t border-gray-100 pt-4 text-xs"><div><p className="text-[10px] uppercase tracking-wide text-gray-400">Link principal</p><p className="mt-1 font-semibold text-gray-800">{item.provedorPrincipal}</p><p className="mt-1 text-gray-500">{item.velocidade} • {item.tecnologia}</p></div><div><p className="text-[10px] uppercase tracking-wide text-gray-400">Contingência</p><p className="mt-1 font-semibold text-gray-800">{item.provedorBackup || "Sem backup"}</p><p className="mt-1 text-gray-500">Suporte {item.telefoneSuporte || "não informado"}</p></div></div><div className="mt-4 flex items-center justify-between rounded-lg bg-gray-50 px-3 py-2 text-[11px] text-gray-500"><span className="flex items-center gap-1.5"><Router className="h-3.5 w-3.5" /> Contrato</span><span className="font-medium text-gray-700">até {item.vencimentoContrato || "—"}</span></div></article>)}{!dados.length && <div className="card p-12 text-center text-sm text-gray-400 md:col-span-2 2xl:col-span-3">Nenhum provedor encontrado.</div>}</div>;
}

function Lista({ dados, onEdit, onDelete }: { dados: ProvedorRegistro[]; onEdit: (item: ProvedorRegistro) => void; onDelete: (item: ProvedorRegistro) => void }) {
  return <section className="card divide-y divide-gray-100 overflow-hidden">{dados.map((item) => <article key={item.id} className="grid items-center gap-4 px-5 py-4 hover:bg-gray-50 md:grid-cols-[minmax(200px,1fr)_minmax(180px,1fr)_minmax(180px,1fr)_120px_90px]"><div><p className="text-sm font-semibold text-gray-900">{item.loja}</p><p className="mt-1 text-xs text-gray-400">{item.cidade}/{item.uf}</p></div><div><p className="text-[10px] uppercase text-gray-400">Principal</p><p className="mt-1 text-xs font-medium text-gray-700">{item.provedorPrincipal} • {item.velocidade}</p></div><div><p className="text-[10px] uppercase text-gray-400">Backup</p><p className="mt-1 text-xs text-gray-600">{item.provedorBackup || "Não informado"}</p></div><Status valor={item.status} /><Acoes item={item} onEdit={onEdit} onDelete={onDelete} /></article>)}{!dados.length && <p className="p-10 text-center text-sm text-gray-400">Nenhum provedor encontrado.</p>}</section>;
}

export default function ProvedoresPage() {
  const [layout, setLayout] = useDataLayout("provedores", "cards");
  const [registros, setRegistros] = useState<ProvedorRegistro[]>(() => PROVEDORES.map((item, index) => ({ ...item, id: `demo-provedor-${index}` })));
  const [busca, setBusca] = useState(""); const [provedor, setProvedor] = useState("Todos"); const [uf, setUf] = useState("Todos"); const [status, setStatus] = useState("Todos");
  const [edicao, setEdicao] = useState<ProvedorRegistro | null>(null); const [salvando, setSalvando] = useState(false); const [erroCrud, setErroCrud] = useState("");
  const [fornecedores, setFornecedores] = useState<Fornecedor[]>([]);
  useEffect(() => { listarProvedores().then(setRegistros).catch(() => undefined); }, []);
  useEffect(() => { listarFornecedores().then((itens) => setFornecedores(itens.filter((item) => item.ativo))).catch(() => undefined); }, []);
  const provedores = useMemo(() => [...new Set(registros.map((item) => item.provedorPrincipal))].sort(), [registros]);
  const estados = useMemo(() => [...new Set(registros.map((item) => item.uf))].sort(), [registros]);
  const dados = registros.filter((item) => { const termo = busca.trim().toLocaleLowerCase("pt-BR"); const texto = Object.values(item).join(" ").toLocaleLowerCase("pt-BR"); return (!termo || texto.includes(termo)) && (provedor === "Todos" || item.provedorPrincipal === provedor) && (uf === "Todos" || item.uf === uf) && (status === "Todos" || item.status === status); });
  const limpar = () => { setBusca(""); setProvedor("Todos"); setUf("Todos"); setStatus("Todos"); };
  const novo = () => setEdicao({ id: "", loja: "", cidade: "", uf: "RJ", provedorPrincipal: "", provedorBackup: "", velocidade: "", tecnologia: "Fibra", status: "Operacional", telefoneSuporte: "", vencimentoContrato: "" });
  const salvar = async () => { if (!edicao) return; if (![edicao.loja, edicao.cidade, edicao.uf, edicao.provedorPrincipal, edicao.velocidade].every((valor) => valor.trim())) { setErroCrud("Preencha os campos obrigatórios."); return; } setSalvando(true); setErroCrud(""); try { setRegistros(await salvarProvedor(edicao)); setEdicao(null); } catch (erro) { setErroCrud(erro instanceof Error ? erro.message : "Erro ao salvar."); } finally { setSalvando(false); } };
  const excluir = async (item: ProvedorRegistro) => { if (!window.confirm(`Excluir o provedor da loja ${item.loja}?`)) return; try { setRegistros(await excluirProvedor(item)); } catch (erro) { window.alert(erro instanceof Error ? erro.message : "Erro ao excluir."); } };
  const porProvedor = provedores.map((nome) => ({ nome, total: dados.filter((item) => item.provedorPrincipal === nome).length })).filter((item) => item.total).sort((a, b) => b.total - a.total);
  const maximo = Math.max(...porProvedor.map((item) => item.total), 1);

  return <div className="page"><div className="page-header gap-4"><div><h1 className="page-title">Provedores de internet</h1><p className="page-subtitle">Links principais e contingências disponíveis em cada loja.</p></div><div className="flex flex-wrap items-center gap-2"><button type="button" onClick={novo} className="btn-primary flex items-center gap-2 text-sm"><Plus className="h-4 w-4" /> Novo provedor</button><DataLayoutSwitcher value={layout} onChange={setLayout} /></div></div>
    <div className="card mb-5 p-4"><div className="grid grid-cols-1 gap-3 sm:grid-cols-2 xl:grid-cols-6"><label className="relative sm:col-span-2"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-gray-400" /><input className="input pl-9" value={busca} onChange={(e) => setBusca(e.target.value)} placeholder="Buscar loja, cidade, provedor, velocidade ou suporte..." /></label><select className="input" value={provedor} onChange={(e) => setProvedor(e.target.value)}><option>Todos</option>{provedores.map((item) => <option key={item}>{item}</option>)}</select><select className="input" value={uf} onChange={(e) => setUf(e.target.value)}><option>Todos</option>{estados.map((item) => <option key={item}>{item}</option>)}</select><select className="input" value={status} onChange={(e) => setStatus(e.target.value)}><option>Todos</option><option>Operacional</option><option>Instável</option><option>Indisponível</option></select><button type="button" onClick={limpar} className="btn-secondary flex w-full items-center justify-center gap-2"><X className="h-4 w-4" /> Limpar</button></div></div>
    {layout === "dashboard" && <div className="space-y-5"><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[{ label: "Lojas filtradas", valor: dados.length, icon: Router, cor: "bg-blue-50 text-blue-600" }, { label: "Links operacionais", valor: dados.filter((item) => item.status === "Operacional").length, icon: Wifi, cor: "bg-green-50 text-green-600" }, { label: "Links com atenção", valor: dados.filter((item) => item.status !== "Operacional").length, icon: Activity, cor: "bg-amber-50 text-amber-600" }, { label: "Cobertura de backup", valor: `${dados.length ? Math.round(dados.filter((item) => item.provedorBackup.trim()).length / dados.length * 100) : 0}%`, icon: ShieldCheck, cor: "bg-violet-50 text-violet-600" }].map(({ label, valor, icon: Icon, cor }) => <div key={label} className="card flex items-center gap-4 p-4"><div className={`flex h-11 w-11 items-center justify-center rounded-xl ${cor}`}><Icon className="h-5 w-5" /></div><div><p className="text-xs text-gray-500">{label}</p><p className="mt-1 text-xl font-semibold text-gray-900">{valor}</p></div></div>)}</div><div className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_minmax(380px,0.6fr)]"><Tabela dados={dados} onEdit={setEdicao} onDelete={excluir} /><section className="card p-5"><h2 className="text-sm font-semibold text-gray-900">Distribuição por provedor</h2><div className="mt-5 space-y-4">{porProvedor.map((item) => <div key={item.nome}><div className="mb-1.5 flex justify-between text-xs"><span className="font-medium text-gray-700">{item.nome}</span><span className="text-gray-500">{item.total}</span></div><div className="h-2 overflow-hidden rounded-full bg-gray-100"><div className="h-full rounded-full bg-brand-600" style={{ width: `${item.total / maximo * 100}%` }} /></div></div>)}</div></section></div></div>}
    {layout === "cards" && <Cards dados={dados} onEdit={setEdicao} onDelete={excluir} />}
    {layout === "list" && <Lista dados={dados} onEdit={setEdicao} onDelete={excluir} />}
    {edicao && <CrudModal titulo={edicao.id ? "Editar provedor" : "Novo provedor"} salvando={salvando} erro={erroCrud} onClose={() => setEdicao(null)} onSave={salvar}><div className="grid gap-4 sm:grid-cols-2">{[["Loja", "loja"], ["Cidade", "cidade"], ["UF", "uf"], ["Velocidade", "velocidade"], ["Telefone do suporte", "telefoneSuporte"], ["Vencimento do contrato", "vencimentoContrato"]].map(([label, campo]) => <label key={campo}><span className="mb-1.5 block text-xs font-medium text-gray-600">{label}{["loja", "cidade", "uf", "velocidade"].includes(campo) ? " *" : ""}</span><input className="input" value={String(edicao[campo as keyof ProvedorRegistro] ?? "")} onChange={(e) => setEdicao((atual) => atual ? { ...atual, [campo]: e.target.value } : atual)} /></label>)}<label><span className="mb-1.5 block text-xs font-medium text-gray-600">Provedor principal *</span><select required className="input" value={edicao.provedorPrincipal} onChange={(e) => setEdicao({ ...edicao, provedorPrincipal: e.target.value })}><option value="">Selecione...</option>{fornecedores.map((item) => <option key={item.id} value={item.nome_fantasia}>{item.nome_fantasia}</option>)}</select></label><label><span className="mb-1.5 block text-xs font-medium text-gray-600">Provedor de backup</span><select className="input" value={edicao.provedorBackup} onChange={(e) => setEdicao({ ...edicao, provedorBackup: e.target.value })}><option value="">Sem backup</option>{fornecedores.map((item) => <option key={item.id} value={item.nome_fantasia}>{item.nome_fantasia}</option>)}</select></label><label><span className="mb-1.5 block text-xs font-medium text-gray-600">Tecnologia</span><select className="input" value={edicao.tecnologia} onChange={(e) => setEdicao({ ...edicao, tecnologia: e.target.value as ProvedorTI["tecnologia"] })}><option>Fibra</option><option>Rádio</option><option>Cabo</option></select></label><label><span className="mb-1.5 block text-xs font-medium text-gray-600">Status</span><select className="input" value={edicao.status} onChange={(e) => setEdicao({ ...edicao, status: e.target.value as ProvedorTI["status"] })}><option>Operacional</option><option>Instável</option><option>Indisponível</option></select></label></div></CrudModal>}
  </div>;
}
