import { useState } from "react";
import { Router, Search, Wifi, WifiOff, X } from "lucide-react";
import { PROVEDORES } from "../data/tiData";

export default function ProvedoresPage() {
  const [busca, setBusca] = useState(""); const [provedor, setProvedor] = useState("Todos"); const [uf, setUf] = useState("Todos"); const [status, setStatus] = useState("Todos");
  const provedores = [...new Set(PROVEDORES.map((item) => item.provedorPrincipal))].sort(); const estados = [...new Set(PROVEDORES.map((item) => item.uf))].sort();
  const dados = PROVEDORES.filter((item) => { const termo = busca.trim().toLocaleLowerCase("pt-BR"); const texto = Object.values(item).join(" ").toLocaleLowerCase("pt-BR"); return (!termo || texto.includes(termo)) && (provedor === "Todos" || item.provedorPrincipal === provedor) && (uf === "Todos" || item.uf === uf) && (status === "Todos" || item.status === status); });
  const limpar = () => { setBusca(""); setProvedor("Todos"); setUf("Todos"); setStatus("Todos"); };
  return <div className="page"><div className="page-header"><div><h1 className="page-title">Provedores de internet</h1><p className="page-subtitle">Links principais e contingências disponíveis em cada loja.</p></div><span className="badge badge-ok">{PROVEDORES.filter((item) => item.status === "Operacional").length} operacionais</span></div>
    <div className="card mb-5 p-4"><div className="grid gap-3 lg:grid-cols-[minmax(260px,1fr)_220px_120px_170px_auto]"><label className="relative"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-gray-400" /><input className="input pl-9" value={busca} onChange={(e) => setBusca(e.target.value)} placeholder="Buscar loja, cidade, provedor, velocidade ou suporte..." /></label><select className="input" value={provedor} onChange={(e) => setProvedor(e.target.value)}><option>Todos</option>{provedores.map((item) => <option key={item}>{item}</option>)}</select><select className="input" value={uf} onChange={(e) => setUf(e.target.value)}><option>Todos</option>{estados.map((item) => <option key={item}>{item}</option>)}</select><select className="input" value={status} onChange={(e) => setStatus(e.target.value)}><option>Todos</option><option>Operacional</option><option>Instável</option><option>Indisponível</option></select><button type="button" onClick={limpar} className="btn-secondary flex items-center justify-center gap-2"><X className="h-4 w-4" /> Limpar</button></div></div>
    <div className="grid gap-4 lg:grid-cols-2">{dados.map((item) => <article key={item.loja} className="card p-5"><div className="flex items-start justify-between gap-4"><div className="flex gap-3"><div className={`flex h-10 w-10 items-center justify-center rounded-xl ${item.status === "Operacional" ? "bg-green-50 text-green-600" : item.status === "Instável" ? "bg-amber-50 text-amber-600" : "bg-red-50 text-red-600"}`}>{item.status === "Indisponível" ? <WifiOff className="h-5 w-5" /> : <Wifi className="h-5 w-5" />}</div><div><h2 className="text-sm font-semibold text-gray-900">{item.loja}</h2><p className="mt-1 text-xs text-gray-400">{item.cidade}/{item.uf}</p></div></div><span className={`badge ${item.status === "Operacional" ? "badge-ok" : item.status === "Instável" ? "badge-warn" : "badge-danger"}`}>{item.status}</span></div>
      <div className="mt-5 grid grid-cols-2 gap-4 border-t border-gray-100 pt-4 text-xs"><div><p className="text-[10px] uppercase tracking-wide text-gray-400">Link principal</p><p className="mt-1 font-semibold text-gray-800">{item.provedorPrincipal}</p><p className="mt-1 text-gray-500">{item.velocidade} • {item.tecnologia}</p></div><div><p className="text-[10px] uppercase tracking-wide text-gray-400">Contingência</p><p className="mt-1 font-semibold text-gray-800">{item.provedorBackup}</p><p className="mt-1 text-gray-500">Suporte {item.telefoneSuporte}</p></div></div><div className="mt-4 flex items-center justify-between rounded-lg bg-gray-50 px-3 py-2 text-[11px] text-gray-500"><span className="flex items-center gap-1.5"><Router className="h-3.5 w-3.5" /> Contrato</span><span className="font-medium text-gray-700">até {item.vencimentoContrato}</span></div>
    </article>)}</div>{dados.length === 0 && <div className="card p-12 text-center text-sm text-gray-400">Nenhum provedor encontrado.</div>}
  </div>;
}
